project:
  type: website

website:
  title: "Nan Nourn នួូនណាន"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    number-sections: true
    anchor-sections: true
    include-in-header:
      - text: |
          <link rel="preconnect" href="https://fonts.googleapis.com">
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
          <link href="https://fonts.googleapis.com/css2?family=Fira+Code:wght@300..700&display=swap" rel="stylesheet">
    monofont: Fira Code
    code-fold: show
    code-link: true
    code-overflow: wrap

execute:
  freeze: auto
