project:
  type: website

website:
  title: "Nan Nourn នួូនណាន"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: quartz
    css: styles.css
    toc: true

execute:
  freeze: auto
